auto: true
permalink: /blog/:year/:month/:day/:title
latest_stable_version: 1.1
latest_stable_url: http://github.com/downloads/davetayls/juxtapo/juxtapo-v1.1.zip
exclude:
- startjekyll.bat
- /portfolio