auto: true
permalink: /blog/:year/:month/:day/:title
latest_stable_version: 1.2.1
latest_stable_url: http://github.com/downloads/davetayls/juxtapo/juxtapo-v1.2.1.zip/qr_code
exclude:
- startjekyll.bat
- /portfolio