/**
 * juxtapo JavaScript Library http://juxtapo.net/
 *
 * Copyright (c) 2009 David Taylor (@davetayls) Licensed under the GNU v3
 * license. http://www.gnu.org/licenses/gpl.html
 * 
 * Version 1.0b
 *
 */

var juxtapo;
(function(e){var a="",c=function(){juxtapo.coreJsUrl()&&juxtapo.utils.requireResource(juxtapo.coreJsUrl()+"juxtapo.css")},b=function(){juxtapo.container=document.createElement("div");e(juxtapo.container).attr("id","juxtapo-container");e("body").append(juxtapo.container)},d=function(){for(var h in juxtapo.plg)if(juxtapo.plg.hasOwnProperty(h)){var i=juxtapo.plg[h];typeof i.init==="function"&&i.init()}},g=function(){var h=juxtapo.utils.getQuery("status");juxtapo.currentStatus=h?h:juxtapo.statuses.pause},f=
function(){e(juxtapo).trigger("_initComplete")},j=function(){e(juxtapo).trigger("_initConfig")};juxtapo={version:"1.0b",statuses:{off:0,play:1,pause:2},designViews:{hidden:0,semiTransparent:1,opaque:2},container:null,controller:null,currentDesignView:0,currentStatus:2,designVisible:false,plg:{},globalSettings:{},coreJsUrl:function(){if(a===""){a=juxtapo.utils.getJsLocation(/juxtapo(\.dev)*\.js/);if(!juxtapo.utils.isAbsoluteUrl(a)){a=juxtapo.utils.resolveAbsoluteUrl(window.location.href,a);juxtapo.eh.logInfo("coreJsUrl: "+
a)}}return a},init:function(){c();j();g();if(juxtapo.currentStatus!==juxtapo.statuses.off){b();juxtapo.templates.init();juxtapo.control.init()}juxtapo.eh.init();juxtapo.thumbs.init();d();f()},addPlugins:function(h){for(var i=0;i<h.length;i+=1){var k=juxtapo.utils.resolveAbsoluteUrl(juxtapo.coreJsUrl(),h[i]);document.write('<script type="text/javascript" src="'+k+'"><\/script>')}},addTemplate:function(h,i,k){if(h instanceof juxtapo.templates.TemplateItem){juxtapo.templates.collection.push(h);return h}else{if(typeof h===
"string")h=[h];h=new juxtapo.templates.TemplateItem(i,h,k);juxtapo.templates.collection.push(h);return h}},setDefaultStyles:function(h){juxtapo.templates.TemplateItem.defaultStyles=h},initConfig:function(h){e(juxtapo).bind("_initConfig",h)},initComplete:function(h){e(juxtapo).bind("_initComplete",h)}};juxtapo.onBody_KeyDown=function(h){var i;if(window.event)i=window.event.keyCode;else if(h)i=h.which;else return true;juxtapo.eh.logInfo("keycode is: "+i);if(h.ctrlKey&&(i===79||i===39)){juxtapo.templates.forward();
juxtapo.utils.preventDefaultEventAction(h);return false}if(h.ctrlKey&&(i===85||i===37)){juxtapo.templates.back();juxtapo.utils.preventDefaultEventAction(h);return false}if(h.ctrlKey&&i===38){juxtapo.templates.change(true);juxtapo.utils.preventDefaultEventAction(h);return false}if(h.ctrlKey&&i===40){juxtapo.templates.change(false);juxtapo.utils.preventDefaultEventAction(h);return false}if(h.ctrlKey&&i===32){juxtapo.control.toggle();juxtapo.utils.preventDefaultEventAction(h);return false}var k=h.shiftKey?
1:25;if(h.ctrlKey&&i===73){juxtapo.templates.nudge("top",k);juxtapo.utils.preventDefaultEventAction(h);return false}if(h.ctrlKey&&i===76){juxtapo.templates.nudge("right",k);juxtapo.utils.preventDefaultEventAction(h);return false}if(h.ctrlKey&&i===75){juxtapo.templates.nudge("bottom",k);juxtapo.utils.preventDefaultEventAction(h);return false}if(h.ctrlKey&&i===74){juxtapo.templates.nudge("left",k);juxtapo.utils.preventDefaultEventAction(h);return false}return true}})(jQuery);
if(window.addEventListener)window.addEventListener("load",juxtapo.init,false);else window.attachEvent&&window.attachEvent("onload",juxtapo.init);
(function(e){var a=null;juxtapo.eh={errors:"",hasError:false,initCompleted:false,dropDown:function(){return a},init:function(){a=new juxtapo.ui.DropDown({style:{height:"300px",width:"450px"}});a.text("e");a.title("Error logger");e(a.contents).addClass("juxtapo-errorBox");juxtapo.eh.renderErrors();this.initCompleted=true},logInfo:function(c){juxtapo.eh.errors='<li class="juxtapo-info">['+juxtapo.utils.date.toShortTimeString(new Date)+"] "+c+"</li>"+juxtapo.eh.errors;juxtapo.eh.renderErrors();return juxtapo.eh.errors},
logError:function(c){if(typeof c==="string")juxtapo.eh.errors='<li class="juxtapo-error">'+c+"</li>"+juxtapo.eh.errors;else if(typeof c==="object")juxtapo.eh.errors='<li class="juxtapo-error">[object]'+juxtapo.utils.objectToStructureString(c)+"</li>"+juxtapo.eh.errors;else juxtapo.eh.errors+='<li class="juxtapo-error">'+c.toString()+"</li>";juxtapo.eh.hasError=true;juxtapo.eh.renderErrors();return juxtapo.eh.errors},renderErrors:function(){if(a){a.contentHtml("<ul>"+juxtapo.eh.errors+"</ul>");e(a.controller).removeClass("juxtapo-eh-error");
if(juxtapo.eh.hasError===true){e(a.controller).addClass("juxtapo-eh-error");a.text("!")}else a.text("e")}return true}};juxtapo.eh.Exception=function(c,b){this.message=c;this.trace=b}})(jQuery);
(function(){juxtapo.control={controller:document.createElement("div"),initCompleted:false,secondsBeforeRefresh:2.5,timerId:-1,init:function(){$(this.controller).attr({"class":"juxtapo-btn",id:"juxtapo-controller",title:"Automatically refresh the page"}).click(this.toggle).appendTo(juxtapo.container);juxtapo.currentStatus===juxtapo.statuses.pause?juxtapo.control.pause():juxtapo.control.play();this.initCompleted=true},play:function(){juxtapo.currentStatus=juxtapo.statuses.play;this.controller.innerHTML=
"|&nbsp;|";this.timerId=setTimeout("juxtapo.control.reload()",this.secondsBeforeRefresh*1E3);return juxtapo.currentStatus},pause:function(){juxtapo.currentStatus=juxtapo.statuses.pause;this.controller.innerHTML=">";clearTimeout(this.timerId);return juxtapo.currentStatus},reload:function(){if(juxtapo.currentStatus===juxtapo.statuses.play){var e=juxtapo.utils.getQuery("jxurl");e=e?unescape(e):location.href;var a=e.indexOf("?")>-1?"&":"?";e=e+a+"jxurl="+escape(e)+"&r="+(new Date).toString()+"&status="+
juxtapo.currentStatus+"&design="+juxtapo.designVisible+"&v="+$(document).scrollTop()+"&dv="+juxtapo.currentDesignView+"&di="+juxtapo.templates.selectedTemplateIndex;location.href=e}},toggle:function(){return juxtapo.currentStatus===juxtapo.statuses.pause?juxtapo.control.play():juxtapo.control.pause()}}})();
(function(){var e=null,a=function(b,d,g){$(juxtapo).trigger("_overlayImagePositionChanged",[b,d,g])},c=function(){$(juxtapo.templates.overlayButton).removeClass("juxtapo-overlayTransparent").removeClass("juxtapo-overlaySemiTrans").removeClass("juxtapo-overlayOpaque")};juxtapo.templates={collection:[],selectedTemplateIndex:0,back:function(){if(juxtapo.currentDesignView===juxtapo.designViews.hidden)juxtapo.templates.show();else juxtapo.currentDesignView===juxtapo.designViews.semiTransparent?juxtapo.templates.hide():
juxtapo.templates.semiTransparent()},change:function(b){if(b){b=juxtapo.templates.selectedTemplateIndex-1;if(b<0)b=juxtapo.templates.collection.length-1}else{b=juxtapo.templates.selectedTemplateIndex+1;if(b>juxtapo.templates.collection.length-1)b=0}juxtapo.templates.changeTo(b)},changeTo:function(b){var d=null;if(typeof b==="undefined")return false;else if(typeof b==="object")d=b;else if(typeof b==="number"&&b<juxtapo.templates.collection.length){juxtapo.templates.selectedTemplateIndex=b;d=juxtapo.templates.collection[b]}if(d){b=
$.extend({},juxtapo.templates.TemplateItem.defaultStyles,d.settings.style);$("#design").attr("src",d.getImageSrc()).css(b)}},selectedTemplateItem:function(){return juxtapo.templates.collection[juxtapo.templates.selectedTemplateIndex]},overlayImageElement:function(b){if(typeof b!=="undefined")e=b;else e||(e=document.getElementById("design"));return e},filterBySearch:function(b){var d=null;if(b==="")$("#juxtapo-thumbs-container .juxtapo-thumb").show();else{d=this.search(b);$("#juxtapo-thumbs-container .juxtapo-thumb").hide();
for(var g=0;g<d.designs.length;g+=1)d.designs[g].thumbnail.show()}return{q:b,designs:d}},forward:function(){if(juxtapo.currentDesignView===juxtapo.designViews.hidden)juxtapo.templates.semiTransparent();else juxtapo.currentDesignView===juxtapo.designViews.semiTransparent?juxtapo.templates.show():juxtapo.templates.hide()},getAll:function(){return juxtapo.templates.collection},getTemplateFromUrl:function(b){b=b.toLowerCase();for(var d=0;d<juxtapo.templates.collection.length;d+=1)for(var g=juxtapo.templates.collection[d],
f=0;f<g.paths.length;f+=1){var j=g.paths[f].toLowerCase();if(b.juxtapoContains(j)){juxtapo.templates.selectedTemplawteIndex=d;return g}}return juxtapo.templates.collection[0]},hide:function(){$("#design").css("display","none");juxtapo.designVisible=false;juxtapo.currentDesignView=juxtapo.designViews.hidden;c();$(this.overlayButton).addClass("juxtapo-overlayTransparent");return juxtapo.currentDesignView},init:function(){$('<img id="design" src="noimage.jpg" alt="design image" />').appendTo("body").css({display:"none"});
juxtapo.utils.getQuery("di")!==null?juxtapo.templates.changeTo(parseInt(juxtapo.utils.getQuery("di"),10)):juxtapo.templates.changeTo(juxtapo.templates.getTemplateFromUrl(location.href));$(document).keydown(juxtapo.onBody_KeyDown);juxtapo.templates.overlayButton=document.createElement("div");$(juxtapo.templates.overlayButton).attr("class","juxtapo-btn");juxtapo.templates.overlayButton.onclick=juxtapo.templates.toggle;juxtapo.templates.overlayButton.innerHTML="OVERLAY";juxtapo.templates.overlayButton.title=
"Toggle visibility of the overlay";juxtapo.container.appendChild(juxtapo.templates.overlayButton);var b=juxtapo.utils.getQuery("design");if(b!==null)juxtapo.designVisible=b;b=juxtapo.utils.getQuery("dv");if(!b)b=juxtapo.currentDesignView;if(b!==null){b=parseInt(b,10);if(b===juxtapo.designViews.hidden)juxtapo.templates.hide();else b===juxtapo.designViews.semiTransparent?juxtapo.templates.semiTransparent():juxtapo.templates.show()}(b=juxtapo.utils.getQuery("v"))&&$(document).scrollTop(b)},nudge:function(b,
d){if(b==="")return false;if(typeof d==="undefined")d=1;var g=$(this.overlayImageElement()),f="margin-left";if(g.css("left").indexOf("%")<0)f=g.css("right")!=="auto"?"right":"left";var j={offSet:g.offset(),position:g.position()};switch(b){case "top":f=parseInt(g.css("top"),10);g.css("top",f-d);break;case "right":b=parseInt(g.css(f),10);f!=="right"?g.css(f,b+d):g.css(f,b-d);break;case "bottom":f=parseInt(g.css("top"),10);g.css("top",f+d);break;case "left":b=parseInt(g.css(f),10);f!=="right"?g.css(f,
b-d):g.css(f,b+d);break}d={offSet:g.offset(),position:g.position()};a(g.get(0),j,d);return this},search:function(b){var d={designs:[],indexes:[]};if(b!==""){b=b.toLowerCase();for(var g=0;g<juxtapo.templates.collection.length;g+=1){var f=juxtapo.templates.collection[g];if(f.imageUrl.toLowerCase().indexOf(b)>-1||f.paths[0].toLowerCase().indexOf(b)>-1){d.designs.push(f);d.indexes.push(g)}}}return d},show:function(){$("#design").css({display:"block",opacity:"1"});juxtapo.designVisible=true;juxtapo.currentDesignView=
juxtapo.designViews.opaque;c();$(this.overlayButton).addClass("juxtapo-overlayOpaque");return juxtapo.currentDesignView},semiTransparent:function(){$("#design").css({display:"block",opacity:"0.5"});juxtapo.designVisible=true;juxtapo.currentDesignView=juxtapo.designViews.semiTransparent;c();$(this.overlayButton).addClass("juxtapo-overlaySemiTrans");return juxtapo.currentDesignView},toggle:function(){juxtapo.templates.forward()},overlayImagePositionChanged:function(b){$(juxtapo).bind("_overlayImagePositionChanged",
b)}};juxtapo.templates.TemplateItem=function(b,d,g){this._init(b,d,g)};juxtapo.templates.TemplateItem.prototype={imageUrl:"",paths:[],settings:{data:{},style:{}},thumbnail:null,_init:function(b,d,g){var f=this;f.imageUrl=b;if(typeof d==="object"&&d.constructor===Array)f.paths=d;else if(typeof d==="string")f.paths=[d];else throw new juxtapo.eh.Exception("Cannot initiate this TemplateItem, valid paths can be a string or array of strings");f.settings=$.extend({},juxtapo.templates.TemplateItem.prototype.settings,
g);f.setUiThumbnail=function(j){f.thumbnail=j;$(f).trigger("_thumbnailSet");return f};f.thumbnailSet=function(j){$(f).bind("_thumbnailSet",j);return f}},getImageSrc:function(){return juxtapo.utils.isRelativeUrl(this.imageUrl)?juxtapo.utils.resolveAbsoluteUrl(juxtapo.coreJsUrl(),this.imageUrl):this.imageUrl}};juxtapo.templates.TemplateItem.defaultStyles={position:"absolute","z-index":"2000",top:"0px",left:"50%","margin-left":"-550px"}})();
(function(){var e;juxtapo.utils={createCookie:function(a,c,b){if(b){var d=new Date;d.setTime(d.getTime()+b*24*60*60*1E3);b="; expires="+d.toGMTString()}else b="";document.cookie=a+"="+c+b+"; path=/";return true},date:{toShortTimeString:function(a){return a.getHours()+":"+a.getMinutes()+":"+a.getSeconds()+":"+a.getMilliseconds()}},eraseCookie:function(a){e.createCookie(a,"",-1);return true},getQuery:function(a){for(var c=window.location.search.substring(1).split("&"),b=0;b<c.length;b+=1){var d=c[b].split("=");
if(d[0]===a)return d[1]}return null},getJsLocation:function(a){if(typeof a==="string")a=new RegExp(a.toLowerCase());for(var c=document.getElementsByTagName("script"),b=0;b<c.length;b+=1){var d=c[b],g=d.src.substring(d.src.lastIndexOf("/")+1).toLowerCase();if(a.test(g))return d.src.substring(0,d.src.lastIndexOf("/")+1)}return null},getKeyCombination:function(a){a=a.split("+");for(var c={ctrl:false,keyCode:-1,shift:false},b=0;b<a.length;b+=1){var d=a[b].toLowerCase();if(isNaN(parseInt(d,10))){c.shift=
c.shift||d==="shift";c.ctrl=c.ctrl||d==="ctrl"}else c.keyCode=parseInt(d,10)}return c},htmlFromTemplate:function(a,c){for(var b in c)if(c.hasOwnProperty(b))a=a.replace(new RegExp("\\${"+b+"}","g"),c[b]);return a},isAbsoluteUrl:function(a){a=a.toLowerCase();if(a.substr(0,7)==="http://")return true;if(a.substr(0,8)==="file:///")return true;if(a.substr(0,6)==="ftp://")return true;return false},isRelativeUrl:function(a){a=a.toLowerCase();if(a.substr(0,2)==="~/")return true;if(a.substr(0,3)==="../")return true;
if(a.substr(0,2)==="./")return true;return false},isStaticUrl:function(a){a=a.toLowerCase();if(a.substr(0,7)==="file://")return true;if(a.substr(0,6)==="ftp://")return true;if(a.substr(1,1)===":")return true;return false},objectToStructureString:function(a,c,b){if(a===window)return"window";if(typeof c==="undefined")c="";if(typeof b==="undefined")b=0;var d="";for(var g in a)if(!(a[g]instanceof Function))if(typeof a[g]==="object"){if(b<3)d+="<li>"+g+":<br />"+juxtapo.utils.objectToStructureString(a[g],
c+"&nbsp;&nbsp;&nbsp;&nbsp;",b+1)+"</li>"}else d+="<li>"+g+":"+a[g]+"</li>";b="";for(var f in a)if(a[f]instanceof Function)b+="<li>"+f+"</li>";a="";if(d!=="")a+="<li>Properties : <ul>"+d+"</ul></li>";if(b!=="")a+="<br />"+c+"<li>Functions : <ul>"+b+"</ul></li>";return"<ul>"+a+"</ul>"},preventDefaultEventAction:function(a){a.preventDefault();a.keyCode=0;a.which=0;if(a.originalEvent)a.originalEvent.keyCode=0},readCookie:function(a){a=a+"=";for(var c=document.cookie.split(";"),b=0;b<c.length;b+=1){for(var d=
c[b];d.charAt(0)===" ";)d=d.substring(1,d.length);if(d.indexOf(a)===0)return d.substring(a.length,d.length)}return null},requireResource:function(a,c){var b=document.getElementsByTagName("head")[0],d=false,g=false;if(a.substr(a.lastIndexOf("."))===".css"){var f=document.createElement("link");f.setAttribute("rel","stylesheet");f.setAttribute("type","text/css");f.setAttribute("href",a);b.appendChild(f);return f}else if(a.substr(a.lastIndexOf("."))===".js"){var j=document.createElement("script");j.type=
"text/javascript";if(typeof c!=="undefined"){j.onreadystatechange=function(){if(this.readyState==="complete"&&!d){g=d=true;typeof c!=="undefined"&&c.call(j,a)}};j.onload=function(){if(!d){g=d=true;typeof c!=="undefined"&&c.call(j,a)}}}j.src=a;$(j).appendTo(b);return j}return null},resolveAbsoluteUrl:function(a,c){if(c.substr(0,1)==="/")return a+c;else if(e.isAbsoluteUrl(c))return c;else{a=a;for(a=a.substring(0,a.lastIndexOf("/"));/^\.\./.test(c);){a=a.substring(0,a.lastIndexOf("/"));c=c.substring(3)}c=
e.String.ltrim(c,"/");return a+"/"+c}},String:{contains:function(a,c){return a.indexOf(c)>-1},ltrim:function(a,c){c=c||"\\s";return a.replace(new RegExp("^["+c+"]+","g"),"")},replace:function(a,c,b){return a.replace(new RegExp("["+c+"]","g"),b)},right:function(a,c){if(c<=0)return"";else if(c>String(a).length)return a;else{var b=String(a).length;return String(a).substring(b,b-c)}},rtrim:function(a,c){c=c||"\\s";return a.replace(new RegExp("["+c+"]+$","g"),"")},trim:function(a,c){return e.String.ltrim(e.String.rtrim(a,
c),c)}}};e=juxtapo.utils;String.prototype.juxtapoContains=function(a){return juxtapo.utils.String.contains(this,a)}})();juxtapo.ui={};
(function(e){var a=null;juxtapo.ui.DropDown=function(c){this._init(c)};juxtapo.ui.DropDown.prototype={afterOpen:null,beforeOpen:null,controller:null,contents:null,expanded:null,settings:{cssClass:"",style:{height:"auto",width:"905px"}},_init:function(c){this.settings=e.extend({},this.settings,c);this.render();var b=this;e(document).bind("keydown",function(d){if(b.expanded&&d.which===27){b.show(false);return false}})},contentHtml:function(c){if(typeof c==="undefined")return e(this.contents).html();
else e(this.contents).html(c)},render:function(){var c=this;this.controller=document.createElement("div");e(this.controller).attr("class","juxtapo-dropDown");this.controller.onclick=function(){c.toggleShow()};juxtapo.container.appendChild(this.controller);this.contents=document.createElement("div");e(this.contents).attr("class","juxtapo-lightBox").css(this.settings.style);document.getElementsByTagName("body")[0].appendChild(this.contents)},show:function(c){if(typeof c==="undefined")c=true;if(c&&!this.expanded){if(a){a.show(false);
a=null}this.beforeOpen&&this.beforeOpen();e(this.contents).show();e(this.controller).addClass("juxtapo-btn-open");this.expanded=true;a=this;this.afterOpen&&this.afterOpen()}else if(!c){e(this.contents).hide();e(this.controller).removeClass("juxtapo-btn-open");this.expanded=false}return this.expanded},text:function(c){if(typeof c==="undefined")return e(this.controller).html();else e(this.controller).html(c);return this},title:function(c){if(typeof c==="undefined")return e(this.controller).attr("title");
else e(this.controller).attr("title",c);return this},toggleShow:function(){return this.show(!this.expanded)}}})(jQuery);
(function(e){juxtapo.ui.Thumbnail=function(a,c){this._init(a,c)};juxtapo.ui.Thumbnail.prototype={container:null,designTemplate:null,settings:{},thumbnailHtmlTemplate:'  <a href="${href}" class="juxtapo-thumb-lnk">    <span class="juxtapo-thumb-img">      <img height="220" alt="design image" src="${imageSrc}">    </span>  </a>  <span class="juxtapo-thumb-caption">    <a href="${href}" tabindex="-1">      ${caption}    </a>  </span>',_init:function(a,c){var b=this;b.settings=e.extend({},this.settings,
c);b.designTemplate=a;b.container=e('<div class="juxtapo-thumb" />').append(juxtapo.utils.htmlFromTemplate(this.getThumbnailHtmlTemplate(),this.getThumbnailData())).get(0);a.setUiThumbnail(b);b.show=function(d){if(typeof d==="undefined")d=true;d?e(b.container).show():e(b.container).hide()}},getImageSrc:function(){return this.designTemplate.getImageSrc()},getLinkHref:function(a){return juxtapo.utils.isRelativeUrl(a)?juxtapo.utils.resolveAbsoluteUrl(juxtapo.coreJsUrl(),a):a},getThumbnailData:function(){return{caption:this.designTemplate.paths[0],
href:this.getLinkHref(this.designTemplate.paths[0]),imageSrc:this.getImageSrc()}},getThumbnailHtmlTemplate:function(){return this.thumbnailHtmlTemplate}}})(jQuery);
(function(){juxtapo.ui.Toolbar=function(e){this._init(e)};juxtapo.ui.Toolbar.prototype={_init:function(e){var a=this;this.settings=$.extend({},this.settings,e);this.toolbar$=$('<div class="juxtapo-ui-toolbar juxtapo-cc" class="juxtapo-cc" />');this.toolbarLeft$=$('<div class="juxtapo-ui-toolbarL juxtapo-cc" />').appendTo(a.toolbar$);this.toolbarRight$=$('<div class="juxtapo-ui-toolbarR juxtapo-cc" />').appendTo(a.toolbar$);this.appendTo=function(c){a.toolbar$.appendTo(c);return a};this.appendLeft=
function(c){a.toolbarLeft$.append(c);return a};this.appendRight=function(c){a.toolbarRight$.append(c);return a}},settings:{}}})();
(function(e){juxtapo.ui.ToolBtn=function(a){this._init(a)};juxtapo.ui.ToolBtn.prototype={container:null,contents:null,settings:{},_init:function(a,c){var b=this;b.settings=e.extend({},this.settings,c);b.contents=e('<span class="juxtapo-toolbtn-contents" />').get(0);b.container=e('<a class="juxtapo-toolbtn" />').append(b.contents).get(0);b.click=function(d){e(b.container).click(d);return b};b.show=function(){e(b.container).show();return b};b.text=function(d){e(b.contents).html(d);return b}}}})(jQuery);
(function(){var e,a=null,c=new juxtapo.ui.Toolbar,b=$('<input id="juxtapo-searchDesigns" type="text" title="Search" />'),d=$('<label><span class="label-text">Search:</span></label>').append(b),g=$('<div id="juxtapo-thumbs-container" />');juxtapo.thumbs={rendered:false,dropDown:function(){return a},init:function(){e=juxtapo.thumbs;a=new juxtapo.ui.DropDown;a.text("+");a.title("View template thumbnails");var f=this;a.beforeOpen=function(){f.rendered||f.renderThumbs()};a.afterOpen=function(){$("#juxtapo-searchDesigns").focus()}},
appendToToolbarLeft:function(f){c.toolbarLeft$.append(f);return e},appendToToolbarRight:function(f){c.toolbarRight$.append(f);return e},renderThumbs:function(){juxtapo.eh.logInfo("thumbs rendering");var f=parseInt($(window).height(),10)-50;$(a.contents).append(c.toolbar$).append(g);c.toolbarLeft$.append(d);g.css("height",f-39+"px");for(f=0;f<juxtapo.templates.collection.length;f+=1){var j=new juxtapo.ui.Thumbnail(juxtapo.templates.collection[f]);g.append(j.container)}b.keyup(this.searchKeyup);this.rendered=
true;$(juxtapo.thumbs).trigger("_thumbsRendered")},searchKeyup:function(){var f=$(this).val();juxtapo.templates.filterBySearch(f)},thumbsContainer:function(){return g.get(0)},thumbsRendered:function(f){$(juxtapo.thumbs).bind("_thumbsRendered",f)}}})();
(function(){var e=null;juxtapo.initComplete(function(){e=new juxtapo.ui.DropDown({style:{width:"300px"}});e.text("?");e.title("Juxtapo help and information");var a="";a="<h4>juxtapo version: "+juxtapo.version+', <a href="http://juxtapo.net">website</a></h4><h4>Keyboard Shortcuts</h4><table width="100%"><tr><td>Move Left</td><td>Ctrl+J [+shift for nudge]</td></tr><tr><td>Move Right</td><td>Ctrl+L [+shift for nudge]</td></tr><tr><td>Move Up</td><td>Ctrl+I [+shift for nudge]</td></tr><tr><td>Move Down</td><td>Ctrl+K [+shift for nudge]</td></tr><tr><td>Transparency Back</td><td>Ctrl+U</td></tr><tr><td>Transparency Forward</td><td>Ctrl+O</td></tr><tr><td>Auto Refresh Play/Stop</td><td>Ctrl+Space</td></tr></table><h4>Documention</h4><ul><li><a href="'+juxtapo.utils.resolveAbsoluteUrl(juxtapo.coreJsUrl(),
"../docs/index.htm")+'">juxtapo API documentation</a></ul>';e.contentHtml(a)})})();
(function(e){juxtapo.Plugin=function(a){if(typeof a==="object")a=a;else if(typeof a==="function"){a=a.call(this);if(typeof a!=="object")a={}}else if(typeof a==="undefined")a={};else throw new juxtapo.eh.Exception("A plugin cannot be instantiated with a "+typeof a);e.extend(this,{},a)};juxtapo.Plugin.prototype={init:function(){if(this.initComplete)return true;if(typeof this._init==="function")try{this._init.call(this)}catch(a){juxtapo.eh.logError(a);return false}this.initComplete=true;this.onInitCompleted();
return true},initComplete:false,initCompleted:function(a){e(this).bind("_initCompleted",a)},onInitCompleted:function(){e(this).trigger("_initCompleted")}}})(jQuery);
