

/**
 * juxtapo JavaScript Library http://juxtapo.net/
 *
 * Copyright (c) 2009 David Taylor (@davetayls) Licensed under the GNU v3
 * license. http://www.gnu.org/licenses/gpl.html
 * 
 * Version 0.6
 *
 */



(function(f){function a(){juxtapo.coreJsUrl()&&juxtapo.utils.requireResource(juxtapo.coreJsUrl()+"juxtapo.css")}function b(){juxtapo.container=document.createElement("div");f(juxtapo.container).attr("id","juxtapo-container");f("body").append(juxtapo.container)}function c(){s=juxtapo.utils.getQuery("status");juxtapo.currentStatus=s?s:juxtapo.statuses.pause}var e="",g=function(){f(juxtapo).trigger("_initComplete")},j=function(){f(juxtapo).trigger("_initConfig")};juxtapo={version:"0.6",statuses:{off:0,
play:1,pause:2},designViews:{hidden:0,semiTransparent:1,opaque:2},container:null,controller:null,currentDesignView:0,currentStatus:2,designVisible:false,designTemplates:[],plugins:{},globalSettings:{},coreJsUrl:function(){if(e=="")e=juxtapo.utils.getJsLocation("juxtapo.js");return e},init:function(){a();j();c();if(juxtapo.currentStatus!=juxtapo.statuses.off){b();juxtapo.templates.init();juxtapo.control.init()}juxtapo.eh.init();juxtapo.thumbs.init();juxtapo.utils.getKeyCombination("13+shift");g()},
addPlugins:function(h){for(var k=0;k<h.length;k++){var l=juxtapo.utils.resolveAbsoluteUrl(juxtapo.coreJsUrl(),h[k]);document.write('<script type="text/javascript" src="'+l+'"><\/script>')}},addTemplate:function(h,k,l){h=new juxtapo.templates.TemplateItem(k,[h],l);this.designTemplates.push(h);return h},setDefaultStyles:function(h){juxtapo.templates.TemplateItem.defaultStyles=h},initConfig:function(h){f(juxtapo).bind("_initConfig",h)},initComplete:function(h){f(juxtapo).bind("_initComplete",h)}};juxtapo.onBody_KeyDown=
function(h){var k;if(window.event)k=window.event.keyCode;else if(h)k=h.which;else return true;juxtapo.eh.logInfo("keycode is: "+k);if(h.ctrlKey&&(k==79||k==39)){juxtapo.templates.forward();juxtapo.utils.preventDefaultEventAction(h);return false}if(h.ctrlKey&&(k==85||k==37)){juxtapo.templates.back();juxtapo.utils.preventDefaultEventAction(h);return false}if(h.ctrlKey&&k==38){juxtapo.templates.change(true);juxtapo.utils.preventDefaultEventAction(h);return false}if(h.ctrlKey&&k==40){juxtapo.templates.change(false);
juxtapo.utils.preventDefaultEventAction(h);return false}if(h.ctrlKey&&k==32){juxtapo.control.toggle();juxtapo.utils.preventDefaultEventAction(h);return false}if(h.ctrlKey&&k==73){k=h.shiftKey?1:25;juxtapo.templates.nudge("top",k);juxtapo.utils.preventDefaultEventAction(h);return false}if(h.ctrlKey&&k==76){k=h.shiftKey?1:25;juxtapo.templates.nudge("right",k);juxtapo.utils.preventDefaultEventAction(h);return false}if(h.ctrlKey&&k==75){k=h.shiftKey?1:25;juxtapo.templates.nudge("bottom",k);juxtapo.utils.preventDefaultEventAction(h);
return false}if(h.ctrlKey&&k==74){k=h.shiftKey?1:25;juxtapo.templates.nudge("left",k);juxtapo.utils.preventDefaultEventAction(h);return false}return true}})(jQuery);if(window.addEventListener)window.addEventListener("load",juxtapo.init,false);else window.attachEvent&&window.attachEvent("onload",juxtapo.init);
(function(){var f=null;juxtapo.eh={errors:"",hasError:false,initCompleted:false,dropDown:function(){return f},init:function(){f=new juxtapo.ui.DropDown({style:{height:"300px",width:"450px"}});f.text("e");$(f.contents).addClass("juxtapo-errorBox");juxtapo.eh.renderErrors();this.initCompleted=true},logInfo:function(a){juxtapo.eh.errors='<li class="juxtapo-info">['+juxtapo.utils.date.toShortTimeString(new Date)+"] "+a+"</li>"+juxtapo.eh.errors;juxtapo.eh.renderErrors();return juxtapo.eh.errors},logError:function(a){if(typeof a==
"string")juxtapo.eh.errors='<li class="juxtapo-error">'+a+"</li>"+juxtapo.eh.errors;else if(typeof a=="object")juxtapo.eh.errors='<li class="juxtapo-error">[object]'+juxtapo.utils.objectToStructureString(a)+"</li>"+juxtapo.eh.errors;else juxtapo.eh.errors+='<li class="juxtapo-error">'+a.message+"</li>";juxtapo.eh.hasError=true;juxtapo.eh.renderErrors();return juxtapo.eh.errors},renderErrors:function(){if(f){f.contentHtml("<ul>"+juxtapo.eh.errors+"</ul>");$(f.controller).removeClass("juxtapo-eh-error");
if(juxtapo.eh.hasError===true){$(f.controller).addClass("juxtapo-eh-error");f.text("!")}else f.text("e")}return true},showErrorBox:function(a){(juxtapo.eh.errorsBoxVisible=a)?$(juxtapo.eh.errorsBox).show(100):$(juxtapo.eh.errorsBox).hide(100)},toggleErrorBox:function(){juxtapo.eh.showErrorBox(!juxtapo.eh.errorsBoxVisible)}}})();
(function(){juxtapo.control={controller:document.createElement("div"),initCompleted:false,secondsBeforeRefresh:2.5,timerId:-1,init:function(){$(this.controller).attr({"class":"juxtapo-btn",id:"juxtapo-controller"}).click(this.toggle).appendTo(juxtapo.container);juxtapo.currentStatus==juxtapo.statuses.pause?juxtapo.control.pause():juxtapo.control.play();this.initCompleted=true},play:function(){juxtapo.currentStatus=juxtapo.statuses.play;this.controller.innerHTML="|&nbsp;|";this.timerId=setTimeout("juxtapo.control.reload()",
this.secondsBeforeRefresh*1E3);return juxtapo.currentStatus},pause:function(){juxtapo.currentStatus=juxtapo.statuses.pause;this.controller.innerHTML=">";clearTimeout(this.timerId);return juxtapo.currentStatus},reload:function(){if(juxtapo.currentStatus==juxtapo.statuses.play){var f=juxtapo.utils.getQuery("jxurl");f=f?unescape(f):location.href;var a=f.indexOf("?")>-1?"&":"?";reloadUrl=f+a+"jxurl="+escape(f)+"&r="+(new Date).toString()+"&status="+juxtapo.currentStatus+"&design="+juxtapo.designVisible+
"&v="+$(document).scrollTop()+"&dv="+juxtapo.currentDesignView+"&di="+juxtapo.templates.selectedTemplateIndex;location.href=reloadUrl}},toggle:function(){return juxtapo.currentStatus==juxtapo.statuses.pause?juxtapo.control.play():juxtapo.control.pause()}}})();
(function(){var f=null,a=function(b,c,e){$(juxtapo).trigger("_overlayImagePositionChanged",[b,c,e])};juxtapo.templates={selectedTemplateIndex:0,back:function(){if(juxtapo.currentDesignView==juxtapo.designViews.hidden)juxtapo.templates.show();else juxtapo.currentDesignView==juxtapo.designViews.semiTransparent?juxtapo.templates.hide():juxtapo.templates.semiTransparent()},change:function(b){if(b){newIndex=juxtapo.templates.selectedTemplateIndex-1;if(newIndex<0)newIndex=juxtapo.designTemplates.length-
1}else{newIndex=juxtapo.templates.selectedTemplateIndex+1;if(newIndex>juxtapo.designTemplates.length-1)newIndex=0}juxtapo.templates.changeTo(newIndex)},changeTo:function(b){var c=null;if(typeof b=="undefined")return false;else if(typeof b=="object")c=b;else if(typeof b=="number"&&b<juxtapo.designTemplates.length){juxtapo.templates.selectedTemplateIndex=b;c=juxtapo.designTemplates[b]}if(c){b=$.extend({},juxtapo.templates.TemplateItem.defaultStyles,c.settings.style);$("#design").attr("src",c.imageUrl).css(b)}},
selectedTemplateItem:function(){return juxtapo.designTemplates[juxtapo.templates.selectedTemplateIndex]},overlayImageElement:function(b){if(typeof b!="undefined")f=b;else f||(f=document.getElementById("design"));return f},filterBySearch:function(b){var c=null;if(b=="")$("#juxtapo-thumbs-container li").show();else{c=this.search(b);$("#juxtapo-thumbs-container li").hide();for(var e=0;e<c.designs.length;e++)c.designs[e].thumbnail.show()}return{q:b,designs:c}},forward:function(){if(juxtapo.currentDesignView==
juxtapo.designViews.hidden)juxtapo.templates.semiTransparent();else juxtapo.currentDesignView==juxtapo.designViews.semiTransparent?juxtapo.templates.show():juxtapo.templates.hide()},getAll:function(){return juxtapo.designTemplates},getTemplateFromUrl:function(b){b=b.toLowerCase();for(var c=0;c<juxtapo.designTemplates.length;c++){layout=juxtapo.designTemplates[c];for(var e=0;e<layout.paths.length;e++){path=layout.paths[e].toLowerCase();if(b.juxtapoContains(path)){juxtapo.templates.selectedTemplawteIndex=
c;return layout}}}return juxtapo.designTemplates[0]},hide:function(){$("#design").css("display","none");juxtapo.designVisible=false;juxtapo.currentDesignView=juxtapo.designViews.hidden},init:function(){$('<img id="design" src="noimage.jpg" alt="design image" />').appendTo("body").css({display:"none"});juxtapo.utils.getQuery("di")!=null?juxtapo.templates.changeTo(parseInt(juxtapo.utils.getQuery("di"))):juxtapo.templates.changeTo(juxtapo.templates.getTemplateFromUrl(location.href));$(document).keydown(juxtapo.onBody_KeyDown);
juxtapo.designlayout=document.createElement("div");$(juxtapo.designlayout).attr("class","juxtapo-btn");juxtapo.designlayout.onclick=juxtapo.templates.toggle;juxtapo.designlayout.innerHTML="D E S I G N";juxtapo.container.appendChild(juxtapo.designlayout);d=juxtapo.utils.getQuery("design");if(d!=null)juxtapo.designVisible=d;dv=juxtapo.utils.getQuery("dv");if(!dv)dv=juxtapo.currentDesignView;if(dv!=null)if(dv==juxtapo.designViews.hidden)juxtapo.templates.hide();else dv==juxtapo.designViews.semiTransparent?
juxtapo.templates.semiTransparent():juxtapo.templates.show();(v=juxtapo.utils.getQuery("v"))&&$(document).scrollTop(v)},nudge:function(b,c){if(b=="")return false;if(typeof c=="undefined")c=1;var e=$(this.overlayImageElement()),g="margin-left";if(e.css("left").indexOf("%")<0)g=e.css("right")!="auto"?"right":"left";var j={offSet:e.offset(),position:e.position()};switch(b){case "top":g=parseInt(e.css("top"));e.css("top",g-c);break;case "right":b=parseInt(e.css(g));g!="right"?e.css(g,b+c):e.css(g,b-c);
break;case "bottom":g=parseInt(e.css("top"));e.css("top",g+c);break;case "left":b=parseInt(e.css(g));g!="right"?e.css(g,b-c):e.css(g,b+c);break}c={offSet:e.offset(),position:e.position()};a(e.get(0),j,c)},search:function(b){var c={designs:[],indexes:[]};if(b!=""){b=b.toLowerCase();for(var e=0;e<juxtapo.designTemplates.length;e++){var g=juxtapo.designTemplates[e];if(g.imageUrl.toLowerCase().indexOf(b)>-1||g.paths[0].toLowerCase().indexOf(b)>-1){c.designs.push(g);c.indexes.push(e)}}}return c},show:function(){$("#design").css({display:"block",
opacity:"1"});juxtapo.designVisible=true;juxtapo.currentDesignView=juxtapo.designViews.opaque;return juxtapo.currentDesignView},semiTransparent:function(){$("#design").css({display:"block",opacity:"0.5"});juxtapo.designVisible=true;juxtapo.currentDesignView=juxtapo.designViews.semiTransparent},toggle:function(){juxtapo.templates.forward()},overlayImagePositionChanged:function(b){$(juxtapo).bind("_overlayImagePositionChanged",b)}};juxtapo.templates.TemplateItem=function(b,c,e){this._init(b,c,e)};juxtapo.templates.TemplateItem.prototype=
{imageUrl:"",paths:[],settings:{data:{},style:{}},thumbnail:null,_init:function(b,c,e){var g=this;g.imageUrl=b;g.paths=c;g.settings=$.extend({},juxtapo.templates.TemplateItem.prototype.settings,e);g.setUiThumbnail=function(j){g.thumbnail=j;$(g).trigger("_thumbnailSet");return g};g.thumbnailSet=function(j){$(g).bind("_thumbnailSet",j);return g}}};juxtapo.templates.TemplateItem.defaultStyles={position:"absolute","z-index":"2000",top:"0px",left:"50%","margin-left":"-550px"}})();
(function(){juxtapo.utils={createCookie:function(a,b,c){if(c){var e=new Date;e.setTime(e.getTime()+c*24*60*60*1E3);c="; expires="+e.toGMTString()}else c="";document.cookie=a+"="+b+c+"; path=/";return true},date:{toShortTimeString:function(a){return a.getHours()+":"+a.getMinutes()+":"+a.getSeconds()+":"+a.getMilliseconds()}},eraseCookie:function(a){f.createCookie(a,"",-1);return true},getQuery:function(a){hu=window.location.search.substring(1);gy=hu.split("&");for(i=0;i<gy.length;i++){ft=gy[i].split("=");
if(ft[0]==a)return ft[1]}return null},getJsLocation:function(a){a=a.toLowerCase();for(var b=document.getElementsByTagName("script"),c=0;c<b.length;c++){var e=b[c],g=e.src.substring(e.src.lastIndexOf("/")+1).toLowerCase();g=g.split("?")[0];if(g==a)return e.src.substring(0,e.src.lastIndexOf("/")+1)}return null},getKeyCombination:function(a){a=a.split("+");for(var b={ctrl:false,keyCode:-1,shift:false},c=0;c<a.length;c++){var e=a[c].toLowerCase();if(isNaN(parseInt(e))){b.shift=b.shift||e=="shift";b.ctrl=
b.ctrl||e=="ctrl"}else b.keyCode=parseInt(e)}return b},isAbsoluteUrl:function(a){Url=a.toLowerCase();if(Url.substr(0,7)=="http://")return true;if(Url.substr(0,6)=="ftp://")return true;return false},isRelativeUrl:function(a){Url=a.toLowerCase();if(Url.substr(0,2)=="~/")return true;if(Url.substr(0,3)=="../")return true;return false},isStaticUrl:function(a){Url=a.toLowerCase();if(Url.substr(0,7)=="file://")return true;if(Url.substr(0,6)=="ftp://")return true;if(Url.substr(1,1)==":")return true;return false},
objectToStructureString:function(a,b,c){if(a==window)return"window";if(typeof b=="undefined")b="";if(typeof c=="undefined")c=0;var e="";for(var g in a)if(!(a[g]instanceof Function))if(typeof a[g]=="object"){if(c<3)e+="<li>"+g+":<br />"+juxtapo.utils.objectToStructureString(a[g],b+"&nbsp;&nbsp;&nbsp;&nbsp;",c+1)+"</li>"}else e+="<li>"+g+":"+a[g]+"</li>";c="";for(var j in a)if(a[j]instanceof Function)c+="<li>"+j+"</li>";a="";if(e!="")a+="<li>Properties : <ul>"+e+"</ul></li>";if(c!="")a+="<br />"+b+
"<li>Functions : <ul>"+c+"</ul></li>";return"<ul>"+a+"</ul>"},preventDefaultEventAction:function(a){a.preventDefault();a.keyCode=0;a.which=0;if(a.originalEvent)a.originalEvent.keyCode=0},readCookie:function(a){a=a+"=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var e=b[c];e.charAt(0)==" ";)e=e.substring(1,e.length);if(e.indexOf(a)==0)return e.substring(a.length,e.length)}return null},requireResource:function(a,b){var c=document.getElementsByTagName("head")[0],e=false,g=false;if(a.substr(a.lastIndexOf("."))==
".css"){var j=document.createElement("link");j.setAttribute("rel","stylesheet");j.setAttribute("type","text/css");j.setAttribute("href",a);c.appendChild(j);return j}else if(a.substr(a.lastIndexOf("."))==".js"){var h=document.createElement("script");h.type="text/javascript";if(typeof b!="undefined"){h.onreadystatechange=function(){if(this.readyState=="complete"&&!e){g=e=true;typeof b!="undefined"&&b.call(h,a)}};h.onload=function(){if(!e){g=e=true;typeof b!="undefined"&&b.call(h,a)}}}h.src=a;$(h).appendTo(c);
return h}return null},resolveAbsoluteUrl:function(a,b){if(b.substr(0,1)=="/")return a+b;else if(f.isAbsoluteUrl(b))return b;else{a=a;for(a=a.substring(0,a.lastIndexOf("/"));/^\.\./.test(b);){a=a.substring(0,a.lastIndexOf("/"));b=b.substring(3)}b=f.String.ltrim(b,"/");return a+"/"+b}},String:{contains:function(a,b){return a.indexOf(b)>-1},ltrim:function(a,b){b=b||"\\s";return a.replace(new RegExp("^["+b+"]+","g"),"")},replace:function(a,b,c){return a.replace(new RegExp("["+b+"]","g"),c)},right:function(a,
b){if(b<=0)return"";else if(b>String(a).length)return a;else{var c=String(a).length;return String(a).substring(c,c-b)}},rtrim:function(a,b){b=b||"\\s";return a.replace(new RegExp("["+b+"]+$","g"),"")},trim:function(a,b){return f.String.ltrim(f.String.rtrim(a,b),b)}}};var f=juxtapo.utils;String.prototype.juxtapoContains=function(a){return juxtapo.utils.String.contains(this,a)}})();juxtapo.ui={};
(function(f){_openDropDown=null;juxtapo.ui.DropDown=function(a){this._init(a)};juxtapo.ui.DropDown.prototype={afterOpen:null,beforeOpen:null,controller:null,contents:null,expanded:null,settings:{cssClass:"",style:{height:"auto",width:"905px"}},_init:function(a){this.settings=f.extend({},this.settings,a);this.render();var b=this;f(document).bind("keydown",function(c){if(b.expanded&&c.which==27){b.show(false);return false}})},contentHtml:function(a){if(typeof a=="undefined")return f(this.contents).html();
else f(this.contents).html(a)},render:function(){var a=this;this.controller=document.createElement("div");f(this.controller).attr("class","juxtapo-dropDown");this.controller.onclick=function(){a.toggleShow()};juxtapo.container.appendChild(this.controller);this.contents=document.createElement("div");f(this.contents).attr("class","juxtapo-lightBox").css(this.settings.style);document.getElementsByTagName("body")[0].appendChild(this.contents)},show:function(a){if(typeof a=="undefined")a=true;if(a&&!this.expanded){if(_openDropDown){_openDropDown.show(false);
_openDropDown=null}this.beforeOpen&&this.beforeOpen();f(this.contents).show();f(this.controller).addClass("juxtapo-btn-open");this.expanded=true;_openDropDown=this;this.afterOpen&&this.afterOpen()}else if(!a){f(this.contents).hide();f(this.controller).removeClass("juxtapo-btn-open");this.expanded=false}return this.expanded},text:function(a){if(typeof a=="undefined")return f(this.controller).html();else f(this.controller).html(a)},toggleShow:function(){return this.show(!this.expanded)}}})(jQuery);
(function(f){juxtapo.ui.Thumbnail=function(a,b){this._init(a,b)};juxtapo.ui.Thumbnail.prototype={caption:null,container:null,designTemplate:null,link:null,imageContainer:null,image:null,settings:{},_init:function(a,b){var c=this;c.settings=f.extend({},this.settings,b);c.designTemplate=a;c.image=f('<img height="220" src="'+a.imageUrl+'" alt="design image" />').get(0);c.imageContainer=f('<span class="juxtapo-thumb-img" />').append(c.image).get(0);c.caption=f('<span class="juxtapo-thumb-caption" />').html(c.designTemplate.paths[0]).get(0);
c.link=f('<a class="juxtapo-thumb-lnk" style="display:block;" href="'+c.designTemplate.paths[0]+'" />').append(c.imageContainer).append(c.caption).get(0);c.container=f('<li class="juxtapo-thumb" />').append(c.link).get(0);a.setUiThumbnail(c);c.show=function(){f(c.container).show()}}}})(jQuery);
(function(f){juxtapo.ui.ToolBtn=function(a){this._init(a)};juxtapo.ui.ToolBtn.prototype={container:null,contents:null,settings:{},_init:function(a,b){var c=this;c.settings=f.extend({},this.settings,b);c.contents=f('<span class="juxtapo-toolbtn-contents" />').get(0);c.container=f('<a class="juxtapo-toolbtn" />').append(c.contents).get(0);c.click=function(e){f(c.container).click(e);return c};c.show=function(){f(c.container).show();return c};c.text=function(e){f(c.contents).html(e);return c}}}})(jQuery);
(function(){juxtapo.ui.Toolbar=function(f){this._init(f)};juxtapo.ui.Toolbar.prototype={_init:function(f){var a=this;this.settings=$.extend({},this.settings,f);this.toolbar$=$('<div class="juxtapo-ui-toolbar juxtapo-cc" class="juxtapo-cc" />');this.toolbarLeft$=$('<div class="juxtapo-ui-toolbarL juxtapo-cc" />').appendTo(a.toolbar$);this.toolbarRight$=$('<div class="juxtapo-ui-toolbarR juxtapo-cc" />').appendTo(a.toolbar$);this.appendTo=function(b){a.toolbar$.appendTo(b);return a};this.appendLeft=
function(b){a.toolbarLeft$.append(b);return a};this.appendRight=function(b){a.toolbarRight$.append(b);return a}},settings:{}}})();
(function(){var f,a=null,b=new juxtapo.ui.Toolbar,c=$('<input id="juxtapo-searchDesigns" type="text" title="Search" />'),e=$('<label><span class="label-text">Search:</span></label>').append(c),g=$('<ul id="juxtapo-thumbs-container" />');juxtapo.thumbs={rendered:false,dropDown:function(){return a},init:function(){f=juxtapo.thumbs;a=new juxtapo.ui.DropDown;a.text("+");var j=this;a.beforeOpen=function(){j.rendered||j.renderThumbs()};a.afterOpen=function(){$("#juxtapo-searchDesigns").focus()}},appendToToolbarLeft:function(j){b.toolbarLeft$.append(j);
return f},appendToToolbarRight:function(j){b.toolbarRight$.append(j);return f},renderThumbs:function(){juxtapo.eh.logInfo("thumbs rendering");var j=parseInt($(window).height())-50;$(a.contents).append(b.toolbar$).append(g);b.toolbarLeft$.append(e);g.css("height",j-39+"px");for(j=0;j<juxtapo.designTemplates.length;j++){var h=new juxtapo.ui.Thumbnail(juxtapo.designTemplates[j]);g.append(h.container)}$("#juxtapo-searchDesigns").keyup(this.searchKeyup);this.rendered=true;$(juxtapo.thumbs).trigger("_thumbsRendered")},
searchKeyup:function(){juxtapo.templates.filterBySearch($("#juxtapo-searchDesigns").val())},thumbsContainer:function(){return g.get(0)},thumbsRendered:function(j){$(juxtapo.thumbs).bind("_thumbsRendered",j)}}})();
(function(){var f=null;juxtapo.initComplete(function(){f=new juxtapo.ui.DropDown({style:{width:"300px"}});f.text("?");var a="";a="<h4>juxtapo version: "+juxtapo.version+', <a href="http://juxtapo.net">website</a></h4><h4>Keyboard Shortcuts</h4><table width="100%"><tr><td>Move Left</td><td>Ctrl+J [+shift for nudge]</td></tr><tr><td>Move Right</td><td>Ctrl+L [+shift for nudge]</td></tr><tr><td>Move Up</td><td>Ctrl+I [+shift for nudge]</td></tr><tr><td>Move Down</td><td>Ctrl+K [+shift for nudge]</td></tr><tr><td>Transparency Back</td><td>Ctrl+U</td></tr><tr><td>Transparency Forward</td><td>Ctrl+O</td></tr><tr><td>Auto Refresh Play/Stop</td><td>Ctrl+Space</td></tr></table><h4>Documention</h4><ul><li><a href="'+juxtapo.utils.resolveAbsoluteUrl(juxtapo.coreJsUrl(),
"../docs/index.htm")+'">juxtapo API documentation</a></ul>';f.contentHtml(a)})})();
